"""Dicionário de critérios para codificação de instrumentos.

Chaves no formato "<Classe> e <Tipo>", com Classe em {Substantivo, Procedimental}
e Tipo em {nodalidade, autoridade, tesouro, organização} (modelo NATO de Hood).
Termos derivados da planilha "exemplos codificação.xlsx" (aba Plan_Python):
informação/informacional -> nodalidade; financeiro -> tesouro;
organizacional -> organização.
"""

import re

CRITERIOS_DIRETOS = {
    "Substantivo e nodalidade": [
        "transparência",
        "acesso à informação",
        "dados abertos",
        "princípio da publicidade",
        "sigilo",
        "Pesquisa e desenvolvimento",
        "Programas para capacitação de recursos humanos",
        "Relatório Estadual",
        "Divulgação, educação e conscientização",
        "Sistema de Registro Nacional de Emissões",
        "Pesquisas e educação para demonstração do papel das florestas plantadas e áreas naturais no ciclo do carbono e como serão afetadas pelas mudanças climáticas",
        "indicadores de sustentabilidade",
        "linhas de pesquisa por agências de fomento",
        "Comunicação Estadual",
        "Sensibilização, conscientização, mobilização e disseminação de informações",
        "Estudos, pesquisas e ações de educação e capacitação nos temas relacionados às mudanças climáticas",
        "Pesquisas sobre as mudanças climáticas, impactos, mitigação, vulnerabilidade adaptação e novas tecnologias",
        "Campanhas de esclarecimento sobre as causas, efeitos relativos aos impactos oriundos de emissões de gases de efeito estufa",
        "Divulgação de informações sobre o impacto de emissões dos produtos e serviços",
        "Estudos, pesquisas e ações de educação e capacitação sobre mudanças climáticas para subsidiar políticas",
        "Pesquisa sobre as mudanças climáticas",
        "Assistência técnica aos municípios sobre transporte sustentável, uso do solo, recuperação florestal, conservação de energia, gerenciamento de resíduos e mitigação de emissões de metano",
        "capacitação da Defesa Civil Estadual",
        "Comunicação Estadual sobre Mudança do Clima",
        "educação e à sensibilização sobre as causas e efeitos da mudança do clima com o objetivo de estimular a adoção de padrões sustentáveis de produção e consumo",
        "linhas de pesquisa sobre ciências em mudança do clima, mitigação, vulnerabilidade, adaptação, desenvolvimento de novas tecnologias",
        "promoção e fomento à pesquisa, ao desenvolvimento, à inovação e à difusão de tecnologias",
        "Registro Estadual de Emissão, Redução e Captura de Gases de Efeito Estufa",
        "educação ambiental e a conscientização social sobre as mudanças climáticas globais",
        "fomento a pesquisas e desenvolvimento na área do transporte sustentável",
        "indicadores em emissões de gases de efeito estufa",
        "pesquisa e a disseminação do conhecimento científico e tecnológico para os temas relativos à proteção do sistema climático",
        "programas de sensibilização, conscientização, mobilização e disseminação de informações",
        "Registro Público de Emissões",
        "divulgação de informações relativas aos programas e às ações de que tratam esta Lei",
        "educação ambiental",
        "incentivo à pesquisa e à criação de modelos de atividades e projetos",
        "incentivo a pesquisas voltadas ao desenvolvimento de tecnologias ambientalmente corretas e ordenadas, bem como à mitigação de externalidades negativas de produção",
        "Comunicação contendo inventários de emissões",
        "Educação e pesquisa científica a respeito do fenômeno das mudanças climáticas",
        "Ações de educação e de conscientização ambiental",
        "Desenvolvimento de pesquisas cientifico-tecnológicas e de difusão de tecnologias sustentáveis",
        "Estudos de vulnerabilidade e de riscos associados às mudanças climáticas para embasar planos",
        "Promoção da educação, da pesquisa e da inovação sobre o tema mudanças e adaptação climáticas",
        "Relatórios de diagnóstico e de gestão de mudanças climáticas",
    ],
    "Substantivo e autoridade": [
        "poder de polícia",
        "competência legal",
        "hierarquia",
        "ordem pública",
        "soberania",
        "lei",
        "Certificado Acre SISA",
        "Programa de Incentivo a Serviços Ambientais - Carbono – ISA Carbono",
        "Programa de Incentivo a Serviços Ambientais da Regulação do Clima – ISA Clima",
        "Programa de Incentivo a Serviços Ambientais da Sociobiodiversidade - ISA Sociobiodiversidade",
        "Programa estadual para conservação dos recursos hídricos",
        "Programa estadual para conservação e melhoramento do solo",
        "Programa estadual para valorização da conservação da beleza cênica natural",
        "Programa estadual para valorização do conhecimento tradicional ecossistêmico",
        "Selo Acre SISA de qualidade",
        "Créditos de carbono jurisdicional",
        "Licenciamento Ambiental",
        "Metas de Redução de Emissões de Gases de Efeito Estufa",
        "Programa de Conservação da Biodiversidade",
        "Programa de Conservação das Águas e dos Recursos Hídricos",
        "Programa de REDD+ Jurisdicional",
        "Salvaguardas Socioambientais",
        "Selos para certificação de produtos e serviços produzidos de forma sustentável",
        "Zoneamento Ecológico-Econômico",
        "Prêmio “Amigo da Floresta e do Clima”",
        "Programa Bolsa Floresta",
        "Programa Estadual de Capacitação de Organismos Públicos e Instituições Privadas",
        "Programa Estadual de Educação sobre Mudanças Climáticas",
        "Programa Estadual de Incentivo à Utilização de Energias Alternativas Limpas e Redutoras da Emissão de Gases de Efeito Estufa",
        "Programa Estadual de Intercâmbio de Tecnologias Limpas e Ambientalmente Responsáveis",
        "Programa Estadual de Monitoramento Ambiental",
        "Programa Estadual de Proteção Ambiental",
        "Selo “Amazonas”",
        "Selo de Certificação “Amigo da Floresta e do Clima”",
        "Código de Proteção de Meio Ambiente",
        "Metas de redução de emissões",
        "Padrões de qualidade ambiental",
        "Plano Estadual de Educação Ambiental",
        "Plano Estadual Estratégico para Redução do Risco de Desastres",
        "Planos de gestão territorial sustentável",
        "Planos setoriais de mitigação e de adaptação às mudanças climáticas",
        "Política Estadual de Educação Ambiental",
        "Políticas municipais de redução de emissões e de adaptação",
        "Programas de conservação e restauração dos biomas Cerrado, Amazônia e Caatinga",
        "Programas de pagamento por serviços ambientais",
        "Programas de prevenção e controle de desmatamento, de incêndios florestais, queimadas",
        "Programas de redução do risco de desastres",
        "Programas de segurança hídrica",
        "Programas para transição energética",
        "Sistema Jurisdicional de REDD+ e PSA",
        "Metas de neutralização de carbono",
        "Certificação de produtos florestais",
        "Inventário Estadual de emissões por fontes e setores de emissão e remoção de gases de efeito estufa",
        "metas de redução de emissões de gases de efeito estufa e metas de eficiência por setor",
        "padrões ambientais e metas, quantificáveis e verificáveis, para a mitigação de emissões antrópicas de gases de efeito estufa",
        "Plano Estadual sobre Mudança do Clima",
        "Plano para Ações Emergenciais - PAE",
        "programas e projetos de sensibilização, mobilização e de disseminação de informações para que a sociedade civil possa efetivamente contribuir com os objetivos desta Lei",
        "selos de reconhecimento público, tanto para a participação no Registro quanto para a comprovação da redução líquida de emissões por redução ou compensação de emissões",
        "zoneamento ecológico-econômico (ZEE)",
        "disciplinamento do uso do solo urbano e rural",
        "inventário das emissões",
        "meta global de redução de emissões",
        "metas de desempenho em emissões de gases de efeito estufa",
        "metas de eficiência e redução setorial",
        "metas para a implantação de ciclovias",
        "Plano Estadual sobre Mudança Climática",
        "Plano Estadual sobre Mudanças Climáticas",
        "planos adequados e integrados para a gestão de zonas costeiras, áreas metropolitanas, recursos hídricos e agricultura, e para a proteção e recuperação de regiões particularmente afetadas por secas e inundações",
        "Planos de Ações Setoriais",
        "veto a concessão de incentivos às atividades que contribuem para emissões de GEE",
        "Zoneamento Ecológico Econômico",
        "inventário estadual, público e privado, de emissões de gases de efeito estufa",
        "Inventário Florístico Florestal de Santa Catarina",
        "licenças ambientais referentes às atividades de projetos no âmbito do Mecanismo de Desenvolvimento Limpo ou de outros mecanismos que visem a mitigação das emissões de gases de efeito estufa",
        "Programa Catarinense de Conservação Ambiental",
        "Programa Catarinense de Educação, Capacitação e Cooperação sobre a Mudança Climática",
        "Programa Catarinense de Estímulo ao Desenvolvimento de Energias Alternativas",
        "Programa Catarinense de Incentivo à Produção e à Utilização de Biocombustíveis",
        "Programa Catarinense de Monitoramento e Inventariamento Ambiental",
        "Programa Catarinense de Mudanças Climáticas",
        "Programa de Incentivo a Redução do Consumo de Energia",
        "Selo de Certificação de Protetor do Clima e o Selo Protetor do Clima Gold",
        "Ações de Mitigação Nacionalmente Apropriadas",
        "Definição de segmentos e atividades econômicas prioritárias para acesso aos instrumentos financeiros",
        "Estabelecimento de critérios e indicadores de sustentabilidade para acesso aos instrumentos financeiros",
        "Estabelecimento de metas",
        "Incorporação de critérios sociais e ambientais nas licitações e contratos do Poder Público Estadual",
        "Incorporação de variáveis de emissões no licenciamento ambiental",
        "Indicadores de sustentabilidade",
        "Iniciativas Estaduais de REDD+",
        "Inventários de emissões",
        "Plano Estadual de Mudanças Climáticas",
        "Programa de defesa civil e auxílio à população voltado à prevenção de danos, ajuda aos necessitados e reconstrução de áreas atingidas por eventos extremos",
        "Programas e Projetos de Mitigação e Compensação das Emissões de Gases de Efeito Estufa",
        "Sistema de previsão de eventos climáticos extremos e alerta rápido para atendimento das necessidades da população",
        "Incorporação de exigência de conformidade com a PEMC aos participantes de licitações",
        "Plano Estadual de Bioeconomia",
        "Programa Estadual de Boas Práticas Produtivas",
        "Programa estadual de Pagamentos por Serviços Ambientais",
        "Programa Estadual de Recuperação da Vegetação Nativa",
        "Programa permanente de defesa civil e de auxílio à população, voltado à prevenção de danos, ajuda aos necessitados e reconstrução de áreas atingidas por eventos extremos decorrentes das mudanças climáticas, eventos climáticos extremos e alerta rápido para atendimento das necessidades da população",
        "Selos para certificação de produtos produzidos de forma sustentável",
        "Sistema de monitoramento e de previsão de eventos climáticos extremos e alerta rápido para atendimento das necessidades da população",
        "Sistema Estadual de Salvaguardas",
        "criação de mercado de reduções compensatórias de emissões de gases de efeito estufa",
        "inventários de emissões de gases causadores do efeito estufa",
        "padrões ambientais",
        "planos de ação",
        "programas de incentivo para a recuperação de matas ciliares",
        "projetos de Mecanismos de Desenvolvimento Limpo",
        "Metas de eficiência setoriais",
        "Metas de redução de emissões de GEE",
        "Programa de Incentivo à Conservação de Serviços Ambientais",
        "Plano Estadual de Redução de Emissões de GEE e Adaptação às Mudanças Climáticas",
        "Programa de Regulação do Clima, Adaptação às Mudanças Climáticas e Qualidade de Vida",
        "Programa de Pagamento por Serviços Ambientais",
        "Transporte sustentável",
        "Disciplinamento do Uso do Solo e Recursos Naturais",
        "Política Estadual de Recursos Hídricos",
        "Plano Estadual de Recursos Hídricos",
        "Planos de Bacias Hidrográficas",
        "Disciplinamento do uso do solo",
        "Metas de redução de emissões de gases de efeito estufa, setoriais ou tecnológicas",
        "Padrões ambientais de qualidade",
        "Política Estadual de Gestão Integrada de Resíduos Sólidos",
        "Plano Estratégico para Ações Emergenciais",
        "Programa de Regularização Ambiental",
        "Metas de estabilização ou redução de emissões",
        "Programa Estadual de Educação Ambiental",
        "Programa Estadual de Incentivo e Intercâmbio de Tecnologias Limpas e Ambientalmente Responsáveis",
        "Programas de fomento a produção de Biodiesel, Etanol, Agricultura e Créditos de Carbono",
        "Metas de redução de desmatamento, conservação e desempenho ambiental",
        "Selo Amigo da Floresta e do Clima",
        "Selo Verde do Tocantins",
    ],
    "Substantivo e tesouro": [
        "transferência",
        "taxas",
        "multa",
        "receita pública",
        "crédito suplementar",
        "Aumento da carga tributária e redução ou revogação de benefício fiscal na aquisição de equipamentos destinados a atividades produtivas que resultem em desmatamento ou que contribuam negativamente para o desenvolvimento dos serviços e produtos ecossistêmicos",
        "Fundo Especial de Meio Ambiente",
        "Fundo Estadual de Florestas",
        "Fundo Nacional sobre Mudanças do Clima",
        "Incentivos econômicos, fiscais, administrativos e creditícios aos beneficiários e proponentes do SISA",
        "Tratamento tributário diferenciado e isenção nas operações",
        "Incentivos econômicos, administrativos e creditícios",
        "Inclusão na Zona Franca Verde de produtos que contribuam para a conservação, recuperação e melhoria dos serviços ambientais",
        "Linhas de crédito e financiamento a juros diferenciados para atividades que promovam a manutenção da integridade dos serviços ambientais",
        "Pagamento por serviços ambientais",
        "Redução de tributos incidentes sobre serviços e ou produtos que promovam a conservação, recuperação e melhoria dos serviços ambientais",
        "Repartição do ICMS com participação diferenciada para municípios que adotem políticas de desenvolvimento sustentável",
        "Tratamento tributário diferenciado e benefícios fiscais",
        "Aumento da carga tributária - redução ou revogação de benefício fiscal, na aquisição de motoserras ou práticas que descumpram a política",
        "Benefícios de redução de base de cálculo ou isenção relativos ao IPVA",
        "Diferimento, redução da base de cálculo, isenção, crédito outorgado e outros incentivos fiscais relativos ao ICMS",
        "Fundo Estadual de Mudanças Climáticas, Conservação Ambiental e Desenvolvimento Sustentável",
        "Mecanismos econômicos e financeiros referentes à mitigação e à adaptação no âmbito da Convenção-Quadro das Nações Unidas sobre Mudança do Clima",
        "Medidas fiscais, tributárias e creditícias, incluindo alíquotas diferenciadas, isenções, compensações e demais incentivos",
        "Desenvolvimento do mercado de carbono",
        "Fundo Estadual de Recursos Hídricos (FRHI/PR)",
        "Fundo Estadual do Meio Ambiente (FEMA)",
        "medidas econômicas, financeiras, fiscais e tributárias destinadas à mitigação de emissões, incluindo alíquotas diferenciadas, isenções, compensações e incentivos",
        "Fundo Estadual de Mudanças Climáticas e Desastres Ambientais",
        "concessão de empréstimos às pessoas físicas e jurídicas de direito privado para a realização de atividades de projetos que visem à estabilização da concentração de gases de efeito estufa e à produção de energias renováveis",
        "Fundo Catarinense de Mudanças Climáticas",
        "incentivos fiscais e tributários",
        "mecanismos financeiros estaduais e nacionais, especialmente os disponibilizados pelo Programa de Desenvolvimento da Empresa Catarinense - PRODEC e pelo Fundo Estadual de Recursos Hídricos - FEHIDRO",
        "Fundo Estadual de Mudanças Climáticas",
        "Incentivos fiscais e financeiros",
        "Linhas de crédito e financiamento",
        "Mecanismo de Desenvolvimento Limpo - MDL",
        "Mecanismo de Redução de Emissão pelo Desmatamento e Degradação Florestal - REDD",
        "Mecanismos financeiros e econômicos",
        "Fundo de Governança Climática e Serviços Ambientais",
        "Crédito voltado a medidas de mitigação de emissões de gases de efeito estufa e de adaptação aos impactos das mudanças climáticas",
        "Preços, tarifas públicas, tributos e outras formas de cobrança por atividades emissoras",
        "Estímulos econômicos para manutenção de florestas existentes, desmatamento evitado e compensação voluntária pelo aumento do estoque florestal",
        "Linhas de crédito e financiamento específicas",
        "Incentivos econômicos e fiscais para geração de energia a partir de fontes renováveis",
        "Fundo Estadual de Recursos Hídricos",
        "Crédito financeiro para medidas de mitigação de emissões de gases de efeito estufa e de adaptação",
        "Preços e tarifas públicas, tributos e outras formas de cobrança por atividades emissoras",
        "Estímulos econômicos para a manutenção e proteção de florestas",
        "Estímulo à projetos que utilizem o Mecanismo de Desenvolvimento Limpo - MDL",
        "Fundo Estadual de Meio Ambiente",
        "Linha de crédito para cadeias produtivas sustentáveis e de desenvolvimento sustentável",
        "Financiamento de atividades de projetos no âmbito do Mecanismo de Desenvolvimento Limpo – MDL, no de Redução de Emissões por Desmatamento – RED",
        "Benefícios econômicos aos produtores agropecuários e florestais que adotem medidas de prevenção, precaução e restauração ambiental",
        "Benefícios de redução de base de cálculo ou isenção relativo ao IPVA",
        "Aumento da carga tributária, mediante a redução ou revogação de benefício fiscal, na aquisição de motoserras ou prática de atos que impliquem o descumprimento da política",
    ],
    "Substantivo e organização": [
        "estrutura administrativa",
        "personalidade jurídica",
        "organograma",
        "cargos e funções",
        "Companhia de Desenvolvimento de Serviços Ambientais",
        "Cooperação com órgãos do governo federal",
        "Instituto de Mudanças Climáticas e Regulação de Serviços Ambientais - IMC",
        "Ouvidoria do SISA",
        "Sistema Estadual de Incentivos a Serviços Ambientais - SISA",
        "Agência de Fomento do Estado do Amapá",
        "Chamadas Públicas",
        "Corpo de Bombeiros do Estado do Amapá",
        "Defesa Civil",
        "Instituto de Extensão, Assistência e Desenvolvimento Rural",
        "Instituto de Pesquisas Científicas e Tecnológicas",
        "Ouvidoria do SECISA",
        "Polícia Militar do Amapá",
        "Secretaria de Desenvolvimento Rural",
        "Secretaria de Estado da Ciência e Tecnologia",
        "Secretaria de Estado da Fazenda",
        "Secretaria de Estado do Meio Ambiente",
        "Sistema Estadual do Clima e Incentivo aos Serviços Ambientais - SECISA",
        "Agência de Fomento do Estado do Amazonas",
        "Centro Estadual de Mudanças Climáticas",
        "Convênios e parcerias com entidades internacionais, nacionais e locais",
        "Instituto de Proteção Ambiental do Amazonas",
        "Secretaria de Estado do Meio Ambiente e Desenvolvimento Sustentável",
        "Sistema Estadual de Educação Ambiental",
        "Sistema Estadual de Meio Ambiente",
        "Secretaria de Estado do Desenvolvimento Ambiental",
        "Sistema Estadual de Governança Climática e Serviços Ambientais",
        "Sistema Estadual de Defesa Civil",
        "Sistema Integrado de Gerenciamento de Recursos Hídricos",
        "Convênios públicos com universidades e institutos",
        "Coordenadoria Estadual de Mudanças Climáticas",
        "Secretaria de Estado do Meio Ambiente e Recursos Hídricos (SEMA)",
        "conveniar com instituições de ensino e pesquisa",
        "organizar o modelo de licitação pública sustentável",
        "Secretaria do Meio Ambiente deverá coordenar a definição de indicadores ambientais",
        "Secretaria Executiva da Política Gaúcha sobre Mudanças Climáticas",
        "convênios e estabelecerá parcerias com entidades internacionais, nacionais e locais para a implementação e desenvolvimento da Política Estadual",
        "estabelecimento de termos de cooperação técnica, científica e econômica no âmbito nacional e internacional, público e privado",
        "instituições financeiras internacionais que utilizem programas de moeda de crédito para emissão, redução e mitigação de GEE",
        "Sistema Estadual de Ciência, Tecnologia e Inovação de Santa Catarina",
        "Sistema Estadual de Unidades de Conservação",
        "Núcleos de adaptação às mudanças do clima e gestão de riscos",
        "Sistema Estadual de Mudanças Climáticas",
        "Corpo de Bombeiros Militar do Estado do Pará",
        "Instituto de Desenvolvimento Florestal e da Biodiversidade",
        "Núcleo de Monitoramento Hidrometeorológico",
        "Secretaria de Estado de Meio Ambiente e Sustentabilidade",
        "Sistema Estadual sobre Mudanças Climáticas",
        "convênios com setores da sociedade civil, universidades, organizações não-governamentais e outras entidades",
        "Secretaria da Ciência e Tecnologia",
        "Secretaria de Recursos Hídricos",
        "Secretaria do Planejamento",
        "Secretaria da Indústria a Comércio",
        "Procuradoria-Geral do Estado",
        "Agência de Fomento do Estado do Tocantins",
        "Instituto Natureza do Tocantins",
    ],
    "Procedimental e nodalidade": [
        "Auditorias externas independentes",
        "Avaliação de impacto ambiental",
        "Etnomapeamento",
        "Monitoramento das emissões",
        "Auditorias externas independentes para avaliar os impactos do programa e seus instrumentos",
        "Avaliação de impacto ambiental e climático de atividades e empreendimentos potencialmente poluidores e/ou utilizadores de recursos ambientais",
        "Monitoramento das emissões atmosféricas e da qualidade do ar",
        "avaliação de impactos ambientais sobre o micro e o macroclima",
        "Avaliação Ambiental Estratégica",
        "Sistema de Contabilidade de Redução de Emissões",
        "monitoramento climático estadual",
        "monitoramento do ciclo hidrológico estadual",
        "monitoramento e estudo do ciclo hidrológico",
        "Estudos de vulnerabilidade e riscos associados às mudanças climáticas para embasar planos",
        "Sistema de registro para ações, programas e projetos monitoráveis e verificáveis de mitigação de redução de emissões de gases de efeito estufa",
    ],
    "Procedimental e autoridade": [
        "Cadastro de empreendimentos",
        "Inventário",
        "Licitação sustentável",
        "Sistema de registro",
        "Inventários Estaduais de serviços ecossistêmicos",
        "Cadastro de empreendimentos que gerem créditos provenientes de ativos ambientais",
        "Registro Público de Emissões e Remoções de Gases de Efeito Estufa",
        "Licitações Sustentáveis",
        "Inventário de emissões",
        "Registro Estadual de Reduções de Emissões",
        "Inventário Estadual de Emissões",
        "Registro Público de Emissões",
    ],
    "Procedimental e tesouro": [
        "dotação orçamentária",
    ],
    "Procedimental e organização": [
        "Comissão Estadual de Validação",
        "Comitê Científico",
        "Coletivo de conselhos",
        "Comitê Técnico-Científico",
        "Conselho Estadual de Meio Ambiente",
        "Fórum Amapaense de Mudanças Climáticas",
        "Núcleo de Adaptação",
        "Fórum Amazonense de Mudanças Climáticas",
        "Comitê Gestor",
        "Conselho Estadual de Recursos Hídricos",
        "Criação de centros de inovação",
        "Fórum Paraense",
        "Fóruns Municipais",
        "Painel científico",
        "Coletivo de conselhos (Conselhos Estaduais de Meio Ambiente, Ciência e Tecnologia, de Florestas e de Desenvolvimento Rural Sustentável)",
        "Comissão Estadual de Validação e Acompanhamento",
        "Conselho Estadual de Meio Ambiente - COEMA",
        "Fórum Amapaense de Mudanças Climáticas e Serviços Ambientais",
        "Núcleo de Adaptação às Mudanças Climáticas e Gestão de Riscos Ambientais",
        "Fórum Maranhense de Mudanças do Clima",
        "Conselho Gestor",
        "Fórum Estadual de Mudanças Climáticas",
        "Comitês de Bacia Hidrográfica",
        "Comitê Intersecretarial de Mudanças Climáticas",
        "Fórum Paranaense de Mudanças Climáticas Globais",
        "Comissão Estadual de Atividades de Meteorologia, Climatologia e Hidrologia",
        "Comissão Intersetorial de Órgãos e Secretarias de Estado",
        "Conselho Estadual do Meio Ambiente",
        "Fórum Gaúcho de Mudanças Climáticas",
        "Rede Brasileira de Pesquisas sobre Mudanças Climáticas e Prevenção de Desastres Naturais – Rede Clima Sul",
        "Fórum Catarinense de Mudanças Climáticas Globais e de Biodiversidade",
        "Consultas públicas",
        "Fórum Mato-grossense de Mudanças Climáticas",
        "Fóruns Municipais de Mudanças Climáticas",
        "Comitê Gestor do Sistema Estadual sobre Mudanças Climáticas",
        "Criação de centros de inovação e de pesquisa",
        "Fórum Paraense de Mudanças e Adaptação Climáticas",
        "Núcleos de Adaptação às Mudanças Climáticas e Gestão de Riscos na Defesa Civil",
        "Painel científico para o Clima",
        "simplificação do procedimento de licenciamento ambiental",
    ],
}

# --- GENERALIZAÇÃO DE TERMOS QUE MENCIONAM ESTADOS ---
# Quando um termo cita um estado (nome ou gentílico), só a parte anterior à menção
# é usada na busca. Ex.: "Fórum Paraense de Mudanças Climáticas" -> "Fórum";
# "Corpo de Bombeiros do Estado do Amapá" -> "Corpo de Bombeiros".
# A regra é aplicada automaticamente a todos os termos, inclusive os adicionados no futuro.
ESTADOS = [
    "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal",
    "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso do Sul", "Mato Grosso",
    "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí",
    "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia",
    "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins",
]
GENTILICOS = [
    "acrean", "alagoan", "amapaense", "amazonense", "baian", "cearense", "brasiliense",
    "capixaba", "goian", "maranhense", "sul-mato-grossense", "mato-grossense",
    "paraense", "paraiban", "paranaense", "pernambucan", "piauiense", "fluminense",
    "potiguar", "gaúch", "rondoniense", "roraimense", "catarinense", "paulista",
    "sergipan", "tocantinense",
]
_PADRAO_ESTADO = re.compile(
    r"(?<![\w-])(?:" + "|".join(re.escape(e) for e in ESTADOS) + r")(?![\w-])"
    r"|(?<![\w-])(?:" + "|".join(re.escape(g) for g in GENTILICOS) + r")[aeo]?s?(?![\w-])",
    re.IGNORECASE,
)
# Conectivos que sobram no fim do termo após o corte (ex.: "... do Estado do")
_SOBRA_FINAL = re.compile(r"(?:\s+(?:do|da|de|dos|das|o|a)|\s+estado|\s*[-–“”\"(,])+\s*$", re.IGNORECASE)


def generalizar_estados(termo):
    """Remove a menção a um estado e tudo o que vem depois dela."""
    menção = _PADRAO_ESTADO.search(termo)
    if not menção:
        return termo
    antes = termo[:menção.start()]
    while True:
        limpo = _SOBRA_FINAL.sub("", antes)
        if limpo == antes:
            break
        antes = limpo
    return antes.strip() or termo


def _generalizar_criterios(criterios):
    resultado = {}
    for categoria, termos in criterios.items():
        vistos, lista = set(), []
        for termo in map(generalizar_estados, termos):
            if termo.lower() not in vistos:
                vistos.add(termo.lower())
                lista.append(termo)
        resultado[categoria] = lista
    return resultado


CRITERIOS_DIRETOS = _generalizar_criterios(CRITERIOS_DIRETOS)
